### ISSUE TITLE
部分华为机器抛出空指针

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#103]
后台监测到部分4.4.2版本的华为机器有坑，抛出空指针，log如下
>java.lang.NullPointerException
 
	at xyz.monkeytong.hongbao.services.HongbaoService.getTheLastNode(HongbaoService.java:228)
 
	at xyz.monkeytong.hongbao.services.HongbaoService.checkNodeInfo(HongbaoService.java:168)
 
	at xyz.monkeytong.hongbao.services.HongbaoService.watchChat(HongbaoService.java:72)
 
	at xyz.monkeytong.hongbao.services.HongbaoService.onAccessibilityEvent(HongbaoService.java:60)
 
	at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:556)
 
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:644)
 
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:40)
 
	at android.os.Handler.dispatchMessage(Handler.java:110)
 
	at android.os.Looper.loop(Looper.java:193)
 
	at android.app.ActivityThread.main(ActivityThread.java:5551)
 
	at java.lang.reflect.Method.invokeNative(Native Method)
 
	at java.lang.reflect.Method.invoke(Method.java:515)
 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
 
	at dalvik.system.NativeStart.main(Native Method)

**Comment by ray26** [comment]
具体信息[http://bughd.com/share/issue/88122d9a0582c2872c89d300c71d0aa0](url)
