### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#43]
```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=3
	at android.util.LongArray.get(LongArray.java:130)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:829)
	at com.miui.hongbao.HongbaoService.checkNodeInfo(HongbaoService.java:150)
	at com.miui.hongbao.HongbaoService.onAccessibilityEvent(HongbaoService.java:79)
	at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
```

**Comment by RussellPeters** [comment]
Process: com.miui.hongbao, PID: 6666
 java.lang.ArrayIndexOutOfBoundsException: length=0; index=3
 at android.util.LongArray.get(LongArray.java:130)
at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:829)
at com.miui.hongbao.HongbaoService.checkNodeInfo(HongbaoService.java:142)
 at com.miui.hongbao.HongbaoService.onAccessibilityEvent(HongbaoService.java:73)
 at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
 at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5466)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
 我这也是

**Comment by ray26** [comment]
@geeeeeeeeek 没有看见更新啊，就是最新的1.4版本出现的这个问题

**Comment by geeeeeeeeek** [comment]
@ray26 我把apk直接换了

**Comment by ray26** [comment]
'''java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
	at android.util.LongArray.get(LongArray.java:130)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:829)
	at com.miui.hongbao.HongbaoService.checkNodeInfo(HongbaoService.java:136)
	at com.miui.hongbao.HongbaoService.onAccessibilityEvent(HongbaoService.java:74)
	at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)'''

**Comment by ray26** [comment]
依旧，把修复代码放上来吧，我也看看怎么修

**Comment by geeeeeeeeek** [comment]
```java
AccessibilityNodeInfo node2 = (this.rootNodeInfo.getChildCount() > 3) ? this.rootNodeInfo.getChild(3) : null;
```

不好意思，刚才`>`写成了`>=`。我以为`AccessibilityNodeInfo.getChild`对越界下标会返回null，没想到直接抛出了异常。

代码和Release都已修改。
