### ISSUE TITLE
null pointer

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#50]
'java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at candy.cream.hongbao.services.HongbaoService.watchList(Unknown Source)
                                                checkNodeInfo
                                                findAccessibilityNodeInfosByTexts
	at candy.cream.hongbao.services.HongbaoService.onAccessibilityEvent(Unknown Source)
	at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)'

**Comment by geeeeeeeeek** [comment]
Got it.
