### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by audiebantzhan** [geeeeeeeeek/WeChatLuckyMoney#65]
在聊天输入`[微信红包]`插件会崩溃

**Comment by ray26** [comment]
能不能提供调试信息，在mi4和flyme无法复现

**Comment by audiebantzhan** [comment]
以下是错误信息：必现
>01-27 15:20:27.324 5423-5423/xyz.monkeytong.hongbao D/AndroidRuntime: Shutting down VM
01-27 15:20:27.328 5423-5423/xyz.monkeytong.hongbao E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: xyz.monkeytong.hongbao, PID: 5423
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.view.accessibility.AccessibilityNodeInfo.getContentDescription()' on a null object reference
                                                                          at xyz.monkeytong.hongbao.services.HongbaoService.watchList(HongbaoService.java:105)
                                                                          at xyz.monkeytong.hongbao.services.HongbaoService.onAccessibilityEvent(HongbaoService.java:59)
                                                                          at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:659)
                                                                          at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:752)
                                                                          at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by geeeeeeeeek** [comment]
```java
List<AccessibilityNodeInfo> nodes = event.getSource().findAccessibilityNodeInfosByText(WECHAT_NOTIFICATION_TIP);
if (!nodes.isEmpty()) {
    AccessibilityNodeInfo nodeToClick = nodes.get(0);
    CharSequence contentDescription = nodeToClick.getContentDescription();
    if (contentDescription != null && !lastContentDescription.equals(contentDescription)) {
        nodeToClick.performAction(AccessibilityNodeInfo.ACTION_CLICK);
        lastContentDescription = contentDescription.toString();
        return true;
    }
}
```
我在前面已经做了`isEmpty`的校验了，`nodeToClick`值为`null`说明`findAccessibilityNodeInfosByText`返回的list中第一个元素是null，这不是函数预期的返回结果，正常情况应该返回empty的list。我认为这是Android的platform_frameworks_base中的一个bug，我在之前调试时遇到过类似的问题，翻了源码记得是有个`checkDataIntegrety`的函数有个地方没有做空值判断，bug的源头可能是多线程导致的。如果说的不对还请指出。

我能做的是多加一个空值判断，但是意义不大，因为底层的bug是不可控的。

**Comment by ray26** [comment]
正在调试

**Comment by geeeeeeeeek** [comment]
@ray26 你调试有什么进展么？我觉得这个bug没有必要修复，你没发现问题的话就关了吧。

我愉快地升级棉花糖MIUI去了。

**Comment by ray26** [comment]
底层bug，无法解决，不过问题不大，复现的概率很小
